services:
  - type: web
    name: canali-italia-stremio
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PLAYLIST_URL
        value: https://raw.githubusercontent.com/diegolasvegas1985-cmd/Canali-Italia/main/italy.m3u
      - key: CACHE_SECONDS
        value: "300"
